# This is a basic workflow to help you get started with Actions

name: 每日打卡

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#   schedule:
#     - cron: '0 2-7/3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Set up timezone
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      # Set up python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      # set up requirement
      - name: install requirement
        run: pip install -r requirement.txt
      - name: report
        env: 
          SETTINGS: ${{ secrets.SETTINGS }}
        run: |
           echo $SETTINGS > "report_setting.json"
           python ./report.py
